trigger:
  branches:
    include:
      - master
      - build-pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Use Node.js 16.x'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Build the project'

  - script: |
      npm test
    displayName: 'Run unit tests'
    continueOnError: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build' 
      ArtifactName: 'drop'
    displayName: 'Publish build artifacts'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/TEST-*.xml'
      testRunTitle: 'Test Results'
    displayName: 'Publish Test Results'